### ISSUE TITLE
Determine single or multiple binaries

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#25]
We have a couple options when it comes to building the application binaries:

* Single application binary with all service controllers
* Multiple application binaries with individual service controllers

**Single application binary**

The approach here is to compile all service controllers into a single application binary. Each service controller will run as a separate Go routine that watches for CRs of types associated with its AWS service API.

Pros:
* Simple installation. One Helm chart that installs a single image as a `Deployment`.
* Simple versioning and upgrade. As simple as one call to `helm upgrade`
* Simple operation. Since it's a single Pod definition, logging and monitoring is inherently easier.

Cons:
* No fine-grained upgrade story. If you want to only upgrade the S3 service controller, you need to update the one image and redeploy the Pod(s)
* If we use IRSA/kIAM/kube2iam for managing a single IAM role for the AWS service permissions, this single IAM role would essentially need superuser privileges on all services. If that is viewed as unacceptable, we'll need to use a technique of using STS::AssumeRole along with a ConfigMap+Secret to map individual AWS service controllers to service-scoped IAM roles.

**Multiple application binaries**

Here, the solution is to compile service controllers into individual application binaries, one for each AWS service API.

Pros:
* Fine-grained installation. Users who want to create only S3 buckets would only install the S3 controller binary
* Fine-grained versioning and upgrade. Users who only want to upgrade to the latest S3 service controller would be able to do that and not impact other service controllers running in the cluster.
* Ability to use IRSA/kIAM/kube2iam with service-scoped IAM role, removing a need for a complex ConfigMap+Secret solution to IAM.

Cons:
* More operational burden. Potentially could have hundreds of these individual service controller binaries in the cluster, each requiring their own logging config, monitoring, etc.
* Much greater versioning complexity. There would need to be a Helm chart per service controller in order to separately version each individual service controller image. Keeping track of these individual service controller versions could prove tricky.
* Many more IAM roles to manage and audit.

**Comment by jaypipes** [comment]
/cc @daviddyball @mhausenblas @ghostsquad

Related: #3

**Comment by daviddyball** [comment]
We run our internal controller as a single binary that contains all controllers for all AWS resources... it hasn't really caused us any issues. Our RBAC policy combined with good CI/CD (including a stage for Open Policy Agent Validation _before_ the resource is even submitted to the API server) means that by the time an `S3Bucket` or `RDSInstance` makes it to the cluster we pretty much trust that the controller should just do what it needs to in order to reconcile the object.

Our AWS Controller IAM role _is_ very permissive, but have mitigations in other places to prevent bad-actors from taking advantage of the AWS Controllers permissions for bad purposes.

I'm very much of the opinion that you shouldn't try to engineer the need for good practices and controlling _what_ makes it to the cluster via good CI/CD practice is, in my opinion, the best way to reduce risk. I think trying to solve everyone's security concerns in the controller itself is a very fast way to over complicate things.

**Comment by daviddyball** [comment]
Also, just to add that upgrades are seamless anyway... releasing a new controller just runs `Reconcile()` on all objects in the cluster and skips over things that are already correct... we've got thousands of custom resources and haven't had any issues with an update breaking things (unless the `Reconcile()` logic itself was bad).

**Comment by jaypipes** [comment]
@daviddyball I'm also in the "prefer a single binary with individual service controllers" bucket, if only because of the simplicity in it and the ability to easily reason about the RBAC and permissions surface area. @anguslees, any thoughts? :)

**Comment by mhausenblas** [comment]
I'm strongly against a single binary since we lose the ability to apply fine-grained RBAC roles in such a case.

**Comment by daviddyball** [comment]
In what sense @mhausenblas? Either way _a_ controller of some sort needs to have RBAC granted for `S3Bucket`... what is the danger of allowing the same controller access to both `S3Bucket` _and_ `DynamoDBTable` ?

**Comment by dcherman** [comment]
Is there a reason not to do both?  If the proposal is to run a goroutine for each CR type, then it seems like you should be able to have a flag like

`--reconcile-types=s3,dynamodb`

Which would allow you to specify exactly which control loops should be running in that instance of the controller.  Omitting that flag would default to "reconcile everything".

That supports the users that wants a simple deployment/single binary that reconciles everything, and the more advanced deployments could be split into N kubernetes deployments, each reconciling a single resource type.

**Comment by daviddyball** [comment]
@dcherman I get what you're saying and configurability is always good, but I don't see what problem this is solving (mainly because I don't think a single binary _is_ a problem). Either way you are going to have to hand over some pretty weighty IAM privileges to any controller you run... so what is the benefit of breaking it down into multiple controllers (and presumably multiple IAM roles for each?)

Is the idea that you'd run
* `namespace-1/s3-controller` with an IAM role called `namespace1-s3-controller`
* `namespace-2/s3-controller` with an IAM role called `namespace2-s3-controller`
And then limit each IAM role to only allow certain things?

In both of those circumstances both controllers still need `s3:CreateBucket` and a host of other things, so I don't see what you're actually protecting yourself from :thinking: 

I guess I just need to understand the scenario people are hoping to solve by splitting it up and running multiple controllers at the same time. It's just never come up as an issue for us... in fact a single binary has made upgrades and IAM management _easier_ in the long run and I don't feel we've weakened our security in either case.

**Comment by marcindulak** [comment]
I'm not sure this is the right place to ask but I'm thinking how dependencies between AWS resources will be handled by ASO? Something like cfn exports/imports. Does this functionality affect the choice of controllers design in any way?

**Comment by mhausenblas** [comment]
Great question @marcindulak and please create a separate issue for this, we should not be discussing it here.

**Comment by jaypipes** [comment]
> I'm strongly against a single binary since we lose the ability to apply fine-grained RBAC roles in such a case.

I'm not sure that is true, @mhausenblas. Let me try to explain.

If you are referring to *RBAC from the Kubernetes perspective*, we would handle that in a validating admission webhook with k8s-native RBAC (either `RoleBinding` or `ClusterRoleBinding` depending on whether the user installed ASO binary in a specific namespace or not). The Kubernetes identity is associated with a Kubernetes Role that is in turn associated with a RoleBinding that indicates what types of CRs the role is allowed to create, patch, delete or list. Each of the AWS service APIs will have one or more types of CRs, and administrators would be able to do really fine-grained RBAC in this way.

When it comes to the *AWS Service API* side of permissions (IAM), it's not set in stone that you would require a single IAM role with permissions to operate on all AWS services. As mentioned in the second "Con" bullet point for the single binary approach in this issue description, I wrote that if we were concerned about a "superuser" single role:

> If that is viewed as unacceptable, we'll need to use a technique of using STS::AssumeRole along with a ConfigMap+Secret to map individual AWS service controllers to service-scoped IAM roles."

Note that I would *prefer* to have a single IAM role that the controller binary runs under because I think that is a simpler model to reason about and audit. But, that said, I don't think having a single application binary necessarily requires us to use a single IAM role for all services.

**Comment by dcherman** [comment]
@jaypipes How would the use of a ConfigMap/Secret with a map of service controllers to service scoped roles increase security?  If the deployment was compromised, the attacker would still have access to assume role on any of the others since a trust relationship needs to exist, meaning that there's really no additional security being introduced, just complexity.  Is that a fair statement?

@daviddyball I don't have a great argument other than to point out that supporting N different controllers does not measurably increase the complexity of the project, so I don't necessarily think it's required for an MVP assuming that the goroutine per resource type model is followed.

That said in your specific example: yes, I would expect that, but that's a different discussion about the CRDs being namespaced.  In the case that you're creating things like S3, DynamoDB, etc.. in a separate micro-account for use in Kubernetes, it's entirely likely that you might have N controllers running in your cluster with different IAM roles depending on what namespace you're working with.

**Comment by daviddyball** [comment]
I agree @dcherman, my example was an attempt to try and understand why multiple-binaries might be a good idea, but even with that example I can't see it being necessary to have multiple binaries when you could use RBAC and IAM to achieve the same thing.

As I see it there is no situation where multiple binaries improves security :man_shrugging:

**Comment by bwagner5** [comment]
I like @dcherman 's suggestion of providing a hybrid solution w/ something like:

```
--reconcile-types=s3,dynamodb
```

That would provide the option to choose if you want to create a bunch of different pods to run the service controllers or the simple option of running them all together. Aside from security this would allow for fine grained upgrades for specific components if you choose to setup your cluster to care about that case.

**Comment by jaypipes** [comment]
All: giving a quick update on this issue. After weighing the pros and cons, we have decided to do the following:

1) Each AWS service API will get its own controller binary. The recommendation will be to use IAM Roles for Service Accounts (alternately: a solution like kube2iam or kiam) in order to isolate a specific AWS service API's permission set to an individual IAM role.

2) In order to address the poorer user experience around managing the lifecycle and management of multiple controller binaries, we will build some tooling that will allow users to generate raw Kubernetes manifests or Helm charts for specified AWS service API controllers. This tooling will (hopefully!) alleviate some of the pain points around IAM role -> Service Account assignment as well. I'm thinking the tooling would facilitate setting up a service controller's IAM role -> Service Account association using some sort of IAM role name template/interpolation scheme.

   For instance, assume this tooling was a `generate-artifacts` script that accepted a list of AWS service APIs to generate service controller `Deployment` and `ServiceAccount` manifests, the user might call this tool like so:

   ```
   generate-manifests ecr s3 sns
   ```

   And by default, the tool would generate a `ServiceAccount` manifest with a `ServiceAccount.Spec.ServiceAccountName` equal to "service-account-$service_alias" (substituting the service's alias of course) and generate `Deployment` manifests that pulled the appropriate service controller binary (the `Deployment.Spec.Template.Spec.Containers[0].Image` value) and set the `Deployment.Spec.Template.Spec.ServiceAccount` to "service-account-$service_alias".

I shall be placing the above into a design document and pushing a PR to the `mvp` branch today. Feel free to provide your feedback and comments either here or in the PR that will be linked to this issue.
