### ISSUE TITLE
replication group custom modify logic

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#413]
**Describe the bug**
    1. Updated logic to handle order of operations when
       failover, multi az are present in desired Spec
    2. Updated logic for Increase, Decrease replicas
       payload to include only those Node Groups
       from desired Spec that have matching nodeGroupId
       present on server
**Steps to reproduce**
   1. Apply replication group yaml with failover false and node group configurations
   2. Apply replication group yaml with Increase/Decrease replicas scenario
       and add node group id which is not present yet on server.
**Expected outcome**
A concise description of what you expected to happen.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.) Elasticache

**Comment by jaypipes** [comment]
@kumargauravsharma hey, quick request... could you update the bug description here to indicate better what the bug is? From what I can understand from the PR, the bug is that if either the automatic failover or multAZ fields are set to false, then we are improperly calling the update replica count or update shard configuration APIs before calling the "normal" ModifyReplicationGroup API. Is that correct? If so, please update the description here :)

**Comment by kumargauravsharma** [comment]
@jaypipes I have updated the defect description.
