### ISSUE TITLE
ECR - updating imageScanningConfiguration of a repository failed

### ISSUE THREAD

**Issue by nithu0115** [aws/aws-controllers-k8s#421]
**Describe the bug**
As part of E2E test, we update the existing repository's imageScanningConfiguration to true. However, I recently started noticing that the update fails. 

output from E2E Smoke test 
```
repository.ecr.services.k8s.aws/ack-test-smoke-ecr-b created
repository.ecr.services.k8s.aws/ack-test-smoke-ecr-c created
Mon Oct 19 16:29:53 CDT 2020
repository.ecr.services.k8s.aws/ack-test-smoke-ecr-b configured
Mon Oct 19 16:29:58 CDT 2020
FAIL: Expected scanning configuration to be 'true' but got 'false'
```
Upon describing the repository, I found that the manifest field for image Scanning Configuration is set to true but I could not see any API calls on CloudTrail Events

```
nithmu@3c22fb382672 ~/g/s/g/a/aws-controllers-k8s (sqs)> kubectl describe repository ack-test-smoke-ecr-b
Name:         ack-test-smoke-ecr-b
Namespace:    default
Labels:       <none>
Annotations:  API Version:  ecr.services.k8s.aws/v1alpha1
Kind:         Repository
Metadata:
  Creation Timestamp:  2020-10-19T21:29:36Z
  Finalizers:
    finalizers.ecr.services.k8s.aws/Repository
  Generation:        2
  Resource Version:  869
  Self Link:         /apis/ecr.services.k8s.aws/v1alpha1/namespaces/default/repositories/ack-test-smoke-ecr-b
  UID:               2e5ef496-7025-4d83-8730-82cff44a315f
Spec:
  Image Scanning Configuration:
    Scan On Push:   true
  Repository Name:  ack-test-smoke-ecr-b
Status:
  Ack Resource Metadata:
    Arn:               arn:aws:ecr:us-west-2:xxxx:repository/ack-test-smoke-ecr-b
    Owner Account ID:  xxxxxx
  Conditions:
  Created At:      2020-10-19T21:29:38Z
  Registry ID:     xxxx
  Repository URI:  xxxx.dkr.ecr.us-west-2.amazonaws.com/ack-test-smoke-ecr-b
Events:            <none>

```

```
{
    "repositories": [
        {
            "repositoryArn": "arn:aws:ecr:us-west-2:xxxx:repository/ack-test-smoke-ecr-b",
            "registryId": "xxxxx",
            "repositoryName": "ack-test-smoke-ecr-b",
            "repositoryUri": "xxxx.dkr.ecr.us-west-2.amazonaws.com/ack-test-smoke-ecr-b",
            "createdAt": "2020-10-19T16:29:38-05:00",
            "imageTagMutability": "MUTABLE",
            "imageScanningConfiguration": {
                "scanOnPush": false
            },
            "encryptionConfiguration": {
                "encryptionType": "AES256"
``` 

**Steps to reproduce**
Run e2e smoke test after creating a kind cluster locally.

**Expected outcome**
The update should change imageScanningConfiguration: true on the ECR repository.

**Environment**
Kind Cluster

**Comment by A-Hilaly** [comment]
After investigating this issue we figured out that the problem is coming from [`pkg/resource/custom_update_api.go`](https://github.com/aws/aws-controllers-k8s/blob/main/services/ecr/pkg/resource/repository/custom_update_api.go#L31-L64): more precisely in the function `customUpdateRepository` which is comparing the `desired` and `latest` objects in order to find the Spec fields that have changed. 
The reason why this is not working as expected is the [`patchResource`](https://github.com/aws/aws-controllers-k8s/blob/main/pkg/runtime/reconciler.go#L210-L216) call in the reconciler. `patchResource` modify the `latest` object to be equal to   `desired` object, since it is [`calling kc.Patch`](https://github.com/aws/aws-controllers-k8s/blob/main/pkg/runtime/reconciler.go#L259-L263) ( see [`StatusWriter.Patch`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L93-L97) )

To correct this issue we should use `diffReporter` to directly get the difference between the desired and latest objects, which is [computed](https://github.com/aws/aws-controllers-k8s/blob/main/pkg/runtime/reconciler.go#L204-L228) before the `patchResource` call. We might also remove `desired` and `latest` parameters from `resourceManager.Update` method.

**Comment by A-Hilaly** [comment]
Just tested updating `imageScanningConfiguration.ScanOnPush` using #531 and it's not failing anymore!
