### ISSUE TITLE
Unable to add helm charts repo for ACK

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#550]
**Describe the bug**
`404 Not Found` error observed during helm repo add.

Reference documentation: https://github.com/aws/aws-controllers-k8s/blob/main/docs/contents/user-docs/install.md 

**Steps to reproduce**
Command:
```
$ helm repo add ack https://aws.github.io/aws-controllers-k8s/charts
```
produces error:
```
Error: looks like "https://aws.github.io/aws-controllers-k8s/charts" is not a valid chart repository or cannot be reached: failed to fetch https://aws.github.io/aws-controllers-k8s/charts/index.yaml : 404 Not Found
```

**Expected outcome**
Repo to get added successfully.

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by jaypipes** [comment]
OK, we identified the source of this problem. Turns out that [the Github Action](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/) we use for auto-generating our docs site is [overwriting](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/master/action.sh#L49) the Git commits in the `gh-pages` branch.

We were storing our Helm Charts in the `charts/` directory of the `gh-pages` branch and unfortunately the last commit that modified the `docs/` content overwrote our Charts. :(

So, I need to regenerate the charts and push them. However, we have decided that since we still have not published our updated install docs that refer to the `gh-pages` Helm Charts repository, we are going to instead publish to a new ECR Public repository and use ECR instead of Dockerhub for storing the binary ACK service controller images.

Please see #461 for information on what we need to do here. I'm going to close this bug out in favor of #461
